#pragma once

/**
 * @file lib_axis_agent.h
 * @brief AXI-Stream verification agent for Verilated designs.
 *
 * Single header containing all declarations for the lib_axis_agent library.
 *
 * ## Components
 * | Class          | Role                                              |
 * |----------------|---------------------------------------------------|
 * | axis_if<BYTES> | DUT signal interface (pointer bundle + direction) |
 *
 * ## Clock discipline
 * Call components in this order on every rising clock edge:
 * @code
 * @endcode
 *
 * @tparam BYTES Data bus width in bytes. Must be a power of two and match
 *               the Verilated model's signal array size.
 *
 */

/**
 * @brief DUT interface
 *
 * Holds raw interface to the AXI-Stream signal members generated by Verilator.
 *
 * @ref Direction enum declares which role this interface plays.
 *
 * ### Example
 * @code
 * axis_if<4> axis_in;
 *
 * axis_in.direction = axis_if<4>::MASTER;
 * axis_in.tvalid    = &dut->t_valid_i;
 * axis_in.tready    = &dut->t_ready_o;
 * axis_in.tdata     = &dut->t_data_i ;
 * axis_in.tkeep     = &dut->t_keep_i ;
 * axis_in.tlast     = &dut->t_last_i;
 * @endcode
 *
 * @tparam BYTES Data bus width in bytes.
 */
template <unsigned BYTES>
struct axis_if {
  /** @brief Declares the direction of this interface operates. */
  enum Direction {
    MASTER, ///< Interface drive TVALID/TDATA/TKEEP/TLAST (transmitter side)
    SLAVE   ///< Interface drives TREADY (receiver side)
  };

  Direction direction = MASTER; ///< Direction of this interface instance

  uint8_t* tvalid = nullptr;
  uint8_t* tready = nullptr;
  uint8_t* tdata  = nullptr;
  uint8_t* tkeep  = nullptr;
  uint8_t* tlast  = nullptr;
 };
