#pragma once

/**
 * @file lib_axis_agent.h
 * @brief AXI-Stream verification agent for Verilated designs.
 *
 * Single header containing all declarations for the lib_axis_agent library.
 *
 * ## Components
 * | Class                     | Role                                              |
 * |---------------------------|---------------------------------------------------|
 * | axis_if<BYTES>            | DUT signal interface (pointer bundle + direction) |
 * |---------------------------|---------------------------------------------------|
 * | axis_transfer<BYTES>      | AXI-Stream transfer container                     |
 * |---------------------------|---------------------------------------------------|
 * | axis_transaction<BYTES>   | AXI-Stream transaction container                  |
 * |---------------------------|---------------------------------------------------|
 * | axis_master_driver<BYTES> | AXI-Stream transmitter component                  |
 * |---------------------------|---------------------------------------------------|
 * | axis_monitor<BYTES>       | AXI-Stream monitor                                |
 *
 * ## Clock discipline
 * Call components in this order on every rising clock edge:
 * @code
 * @endcode
 *
 * @tparam BYTES Data bus width in bytes. Must be a power of two and match
 *               the Verilated model's signal array size.
 *
 */

 #include "verilated.h"
 #include <cstdint>
 #include <vector>
 #include <queue>
 #include <cstring>
 #include <functional>

/**
 * @brief DUT interface
 *
 * Holds raw interface to the AXI-Stream signal members generated by Verilator.
 *
 * @ref Direction enum declares which role this interface plays.
 *
 * ### Example
 * @code
 * axis_if<4> axis_in;
 *
 * axis_in.direction = axis_if<4>::MASTER;
 * axis_in.tvalid    = &dut->t_valid_i;
 * axis_in.tready    = &dut->t_ready_o;
 * axis_in.tdata     = &dut->t_data_i ;
 * axis_in.tkeep     = &dut->t_keep_i ;
 * axis_in.tlast     = &dut->t_last_i;
 * @endcode
 *
 * @tparam BYTES Data bus width in bytes.
 */
template <unsigned BYTES>
struct axis_if {
  /** @brief Declares the direction of this interface operates. */
  enum Direction {
    MASTER, ///< Interface drive TVALID/TDATA/TKEEP/TLAST (transmitter side)
    SLAVE   ///< Interface drives TREADY (receiver side)
  };

  Direction direction = MASTER; ///< Direction of this interface instance

  // Pointers to DUT ports
  uint8_t* tvalid = nullptr;
  uint8_t* tready = nullptr;
  uint8_t* tlast  = nullptr;
  void*    tdata  = nullptr;
  void*    tkeep  = nullptr;

  // For agent's internal use
  uint8_t data[BYTES] = {};
  uint8_t keep[BYTES] = {};

  /**
   * @brief Synchronize with the DUT
   *
   */
  void update() {
    if (direction == MASTER) { // To DUT
      if (tdata) {
        if constexpr (BYTES == 1) {
          *static_cast<CData*>(tdata) = data[0];
        } else if (BYTES == 2) {
          SData v;
          std::memcpy(&v,data,BYTES);
          *static_cast<SData*>(tdata) = v;
        } else if (BYTES == 4) {
          IData v;
          std::memcpy(&v,data,BYTES);
          *static_cast<IData*>(tdata) = v;
        } else if (BYTES == 8) {
          QData v;
          std::memcpy(&v,data,BYTES);
          *static_cast<QData*>(tdata) = v;
        }
      } // tdata

      if (tkeep) {
        uint8_t packed;

        packed = 0;

        for (unsigned i=0; i<BYTES; i++) {
          if (keep[i]) {
            packed |= (1u << i);
          }
        }

        *static_cast<CData*>(tkeep) = packed;
      } // tkeep

    } else { // From DUT
      if (tdata) {
        if constexpr (BYTES == 1) {
          data[0] = *static_cast<CData*>(tdata);
        } else if (BYTES == 2) {
          SData v;
          v = *static_cast<SData*>(tdata);
          std::memcpy(data,&v,BYTES);
        } else if (BYTES == 4) {
          IData v;
          v = *static_cast<SData*>(tdata);
          std::memcpy(data,&v,BYTES);
        } else if (BYTES == 8) {
          QData v;
          v = *static_cast<QData*>(tdata);
          std::memcpy(data,&v,BYTES);
        }
      }

      if (tkeep) {
        keep[0] = *static_cast<CData*>(tkeep);
      }
    } // if (direction == MASTER)
  }
};

 /**
  * @brief One AXI-Stream transfer.
  *
  * Captures the state of TDATA, TKEEP, and TLAST during an acknowledged transfer.
  *
  * @tparam BYTES Data bus width in bytes.
  */
template <unsigned BYTES>
struct axis_transfer {
  uint8_t tdata[BYTES] = {};    ///< Data bytes for each lane
  uint8_t tkeep[BYTES] = {};    ///< BYte-enable
  bool    tlast        = false; ///< Last transfer indicator

  /**
   * @brief Build a transfer from an array of valid bytes.
   *
   * Fills @c tdata and @c tkeep from @p src for the first @p n_valid bytes.
   * Bytes beyond @p n_valid have @c tkeep=0.
   * Sets @c tlast to @p last.
   *
   * @param src     Pointer to byte array (left-justified).
   * @param n_valid Number of valid bytes in @p src. May be less than BYTES.
   * @param last    Value to assign @c tlast.
   * @return        Populated axis_transfer.
   */
  static axis_transfer from_bytes(const uint8_t* src, unsigned n_valid, bool last) {
    axis_transfer transfer;

    for (unsigned i = 0; i < BYTES; i++) {
      if (i < n_valid) {
        transfer.tdata[i] = src[i];
        transfer.tkeep[i] = 1;
      }
      else {
        transfer.tdata[i] = 0;
        transfer.tkeep[i] = 0;
      }
    }

    transfer.tlast = last;

    return transfer;
  }
};



/**
 * @brief Sequence of transfers forming one AXI-Stream transaction.
 *
 * A transaction ends with the transfer that has @c tlast=1.
 *
 * @tparam BYTES Data bus width in bytes.
 */
template <unsigned BYTES>
struct axis_transaction {
  std::vector<axis_transfer<BYTES>> transfers; ///< Transfers making up the transaction

  /**
   * @brief Build a transaction from a byte vector.
   *
   * Splits @p data into BYTES-wide transfers.
   * The last transfer has @c tlast asserted.
   * @c tkeep for the invalid bytes in partial final transfers is deasserted.
   *
   * @param data Payload bytes buffer.
   * @return     Populated axis_transaction.
   */
  static axis_transaction from_bytes(const std::vector<uint8_t>& data) {
    axis_transaction txn;
    unsigned off = 0;

    //TODO: throw exception if data is empty?
    while (off < data.size()) {
      unsigned remaining = static_cast<unsigned>(data.size()) - off;
      bool     last      = (remaining <= BYTES);

      txn.transfers.push_back(
        axis_transfer<BYTES>::from_bytes(data.data() + off, remaining, last));

      off += BYTES;
    }

    return txn;
  }

  /**
  * @brief Build a transaction from a vector of Verilator-native words.
  *
  * Each word represents one full transfer's worth of data, matching the
  * Verilator type Verilator itself would generate for a TDATA signal of
  * this width (CData/SData/IData/QData for 1/2/4/8 bytes respectively).
  *
  * @tparam WORD_T Verilator word type. Must be CData, SData, IData, or
  *                QData, matching BYTES exactly.
  * @param words   Vector of words, one per transfer.
  * @return        Populated axis_transaction with one transfer per word,
  *                tlast=1 on the final word, full tkeep (all lanes valid).
  */
  template <typename WORD_T>
  static axis_transaction from_words(const std::vector<WORD_T>& words) {
    static_assert(sizeof(WORD_T) == BYTES,
      "from_words: WORD_T size must match BYTES "
      "(use CData/SData/IData/QData matching the bus width)");

    axis_transaction txn;

    for (std::size_t i = 0; i < words.size(); ++i) {
      axis_transfer<BYTES> t;

      std::memcpy(t.tdata, &words[i], BYTES);

      std::memset(t.tkeep, 1, BYTES); // full word — all lanes valid

      t.tlast = (i == words.size() - 1);

      txn.transfers.push_back(t);
    }
    return txn;
  }

  /**
   * @brief Flatten all valid bytes back into a byte vector.
   *
   * Only bytes whose @c tkeep lane is set are included.
   *
   * @return Flat byte vector of the transaction payload.
   */
  std::vector<uint8_t> to_bytes() const {
    std::vector<uint8_t> out;

    for (auto& t: transfers) {
      for (unsigned i = 0; i < BYTES; i++) {
        if (t.tkeep[i]) {
          out.push_back(t.tdata[i]);
        }
      }
    }

    return out;
  }

  /**
   * @brief Returns true if transaction contains no transfers.
   */
  bool empty() const {
    return transfers.empty();
  }
};


/**
 * @brief AXI-Stream Master Driver
 *
 * Drives AXI-Stream bus on MASTER @ref axis_if.
 *
 * ### Usage
 *
 * @code
 * axis_master_driver<4> driver(in_if);
 * driver.send_bytes({0xDE, 0xAD, 0xBE, 0xEF});
 *
 * // In clock loop, before dut->eval();
 * driver.eval();
 * @endcode
 *
 * @tparam BYTES Data bus width in bytes.
 */
template <unsigned BYTES>
class axis_master_driver {
  public:
    using Transaction = axis_transaction<BYTES>;
    using Transfer    = axis_transfer<BYTES>;

    /**
     * @brief Callback type invoked when transaction finishes transmitting.
     * @param txn the completed transaction.
     */
    using DoneCB =  std::function<void(const Transaction& txn)>;

    /**
     * @brief Constructs a master driver bound to @p mif.
     *
     * @param mif   Master AXI-Stream interface to the DUT.
     * @param done  Optional callback evoked after transmission is done.
     *
     * @throws std::invalid_argument if @p mif.direction != MASTER.
     */
    explicit axis_master_driver(axis_if<BYTES>& mif, DoneCB done = nullptr);

    /**
     * @brief Transmits data bytes contained in an axis_transaction struct.
     *
     * @param txn Transaction to send.
     */
    void send_txn(const Transaction& txn);


    /**
     * @brief Transmits data bytes contained in a buffer in an AxI-Stream transaction.
     *
     * @param byte_vec Byte vector to send as a single transaction.
     */
    void send_bytes(const std::vector<uint8_t>& byte_vec);

    /**
     * @brief Advance the driver component by one clock cycle.
     *
     * Must be called on every rising clock edge before dut->eval().
     */
    void eval();

    /**
     * @brief Returns true when the queue is empty and no transfer is in flight.
     */
    bool is_idle() const;

    /**
     * @brief Returns the number of transactions currently waiting in the queue.
     */
    std::size_t queued_transactions() const;

    /**
     * @brief Replace the done callback.
     *
     * @param cb New callback, or nullprt to disable.
     */
    void set_done_cb(DoneCB cb);

  private:
    axis_if<BYTES>&         mif_;
    DoneCB                  done_;
    std::queue<Transaction> queue_;
    Transaction             current_txn_;
    unsigned                transfer_idx_     = 0;
    bool                    transfer_pending_ = false;

    void drive(const Transfer& t);
    void deassert();

    /**
     * @brief Advance to the next transfer, fire on_done_ and reset state at end-of-transaction.
     */
    void advance();
};


/**
 * @brief AXI-Stream Monitor
 *
 * Captures AXI-Stream bus traffic to and from the DUT.
 *
 * Stores completed transactions in an internal queue that
 * can be retrieved with @ref pop_transaction().
 *
 * A callback can be fired on each completed transaction
 *
 * ### Usage
 *
 * @code
 * axis_monitor<4> mon(_if, on_monitor_txn);
 * driver.send_bytes({0xDE, 0xAD, 0xBE, 0xEF});
 *
 * // In clock loop, after dut->eval();
 * mon.eval();
 * @endcode
 *
 * @tparam BYTES Data bus width in bytes.
 */
template <unsigned BYTES>
class axis_monitor {
  public:
    using Transaction = axis_transaction<BYTES>;

    /**
     * @brief Callback type invoked when a complete transaction is captured.
     * @param txn the completed transaction.
     */
    using TxnCB =  std::function<void(const Transaction& txn)>;

    /**
     * @brief Constructs a monitor bound to @p iface.
     *
     * @param iface  Master AXI-Stream interface to the DUT.
     * @param on_txn Optional callback evoked after transmission is done.
     */
    explicit axis_monitor(const axis_if<BYTES>& iface, TxnCB on_txn = nullptr);

    /**
     * @brief Sample the bus and update internal state.
     *
     * Must be called on every rising clock edge after @c dut->eval().
     */
    void eval();

    /**
     * @brief Returns TRUE if there is at least one transaction in the queue.
     */
    bool has_transaction() const;

    /**
     * @brief Remove and return the oldest completed transaction from the queue.
     *
     * @return The oldest completed transaction.
     */
    Transaction pop_transaction();

    /**
     * @brief Returns the number of completed transactions currently queued.
     */
    std::size_t rx_count() const;

    /**
     * @brief Replace the on_txn callback.
     *
     * @param cb New callback, or nullptr to disable.
     */
    void set_transaction_cb(TxnCB cb);

  private:
    axis_if<BYTES>          iface_;
    TxnCB                   on_txn_;
    std::queue<Transaction> rx_queue_;
    Transaction             current_;
};

template <unsigned BYTES>
class axis_agent {
  public:
    enum AgentMode {ACTIVE, PASSIVE};

    using Transaction = axis_transaction<BYTES>;
    using DoneCB      = typename axis_master_driver<BYTES>::DoneCB;
    using TxnCB       = typename axis_monitor<BYTES>::TxnCB;

    /**
     * @brief Constructs the AXI-stream agent bound to @p mif.
     *
     * @param iface           Interface to the DUT.
     * @param mode            ACTIVE adds a driver; PASSIVE creates monitor only.
     * @param on_driver_done  Optional callback evoked after transmission is done.
     * @param on_monitor_done Optional callback evoked after an AXI-S transaction is captured.
     *
     * @throws std::invalid_argument if @p iface.direction doesn't match @p mode.
     */
    explicit axis_agent(axis_if<BYTES>& iface,
                        AgentMode       mode = ACTIVE,
                        DoneCB          on_driver_done  = nullptr,
                        TxnCB           on_monitor_done = nullptr);

    axis_master_driver<BYTES>* driver()  { return driver_.get(); }
    axis_monitor<BYTES>&       monitor() { return monitor_;      }

    void pre_eval();
    void post_eval();
    void send_txn(const Transaction& txn);
    bool is_idle() const;
    std::size_t queued_transactions() const;

  private:
    axis_if<BYTES>& iface_;
    AgentMode       mode_;

    // components
    std::unique_ptr<axis_master_driver<BYTES>> driver_;
    axis_monitor<BYTES>                        monitor_;
};
